### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/ATMCDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
### WEB SERVICE ###
server.port=8089
server.servlet.context-path=/ATMC
# Swagger URL :
# http://localhost:8089/ATMC/swagger-ui/index.html
